# Tranquilpeak
# Version : 0.2.0-ALPHA
# Author : Thibaud Leprêtre

# I STRONGLY recommend you to use a CDN to speed up loading of pages.
# There is many free CDN like Cloudinary or you can also use indirectly
# by using services like Google Photos.

# If you want to store images yourself, please read this guidelines:
# For users, if you only use this theme, put your images directly in `source/assets/images` folder
# But if you want to add local images, you can put your images directly in `source/assets/images` folder
# For developpers, if you modify this theme, put your images in `source/images` folder and
# use grunt task `build` to synchronize assets

baseurl = "https://dawnarc.com/"
title = "玄冬Wong"
theme = "hugo-tranquilpeak-theme"
canonifyurls = true

# Enable emoji support
enableEmoji = true

# Enable Git info for lastmod
enableGitInfo = true

DefaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

# hide Post menu
sectionPagesMenu = ""

[params.author]
  name = "Wang Aiguo"
  bio = "山河固，九边殊，万里川原，龙旗指处。"
  job = "Developer"
  location = "Yichang, Hubei"
  avatar = "/avatar.jpg"

[languages]
  [languages.en]
    title = "玄冬Wong"
    languageName = "English"
    weight = 1
    [languages.en.pagination]
      disableAliases = true
      pagerSize = 15
      path = 'page'

[permalinks]
  post = "/:year/:month/:slug/"

[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"

# Navigation Menu
[menu]
  [[menu.main]]
    weight = 1
    name = "Home"
    identifier = "home"
    url = "/"
    pre = "<i class=\"sidebar-button-icon fa fa-lg fa-home\"></i>"
  [[menu.main]]
    weight = 2
    name = "Categories"
    identifier = "categories"
    url = "/categories"
    pre = "<i class=\"sidebar-button-icon fa fa-lg fa-bookmark\"></i>"
  [[menu.main]]
    weight = 3
    name = "Archives"
    identifier = "archives"
    url = "/archives"
    pre = "<i class=\"sidebar-button-icon fa fa-lg fa-archive\"></i>"
  [[menu.main]]
    weight = 4
    name = "Tags"
    identifier = "tags"
    url = "/tags"
    pre = "<i class=\"sidebar-button-icon fa fa-lg fa-tags\"></i>"
  [[menu.main]]
    weight = 5
    name = "About"
    identifier = "about"
    url = "/#about"
    pre = "<i class=\"sidebar-button-icon fa fa-lg fa-question\"></i>"
  [[menu.main]]
    weight = 6
    name = "RSS"
    identifier = "rss"
    url = "/index.xml"
    pre = "<i class=\"sidebar-button-icon fa fa-lg fa-rss\"></i>"

[[menu.links]]
  weight = 0
  identifier = "github"
  name = "GitHub"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-github\"></i>"
  url = "https://github.com/dawnarc"
[[menu.links]]
  weight = 1
  identifier = "stackoverflow"
  name = "Stack Overflow"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-stack-overflow\"></i>"
  url = "https://stackoverflow.com/users/1645289/protoss"
[[menu.links]]
  weight = 0
  identifier = "twitter"
  name = "Twitter"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-twitter\"></i>"
  url = "https://twitter.com/dawn_arc"
[[menu.links]]
  weight = 0
  identifier = "facebook"
  name = "Facebook"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-facebook\"></i>"
  url = "https://www.facebook.com/koanland"
[[menu.links]]
  weight = 0
  identifier = "weibo"
  name = "Weibo"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-weibo\"></i>"
  url = "https://weibo.com/koanland"
[[menu.links]]
  weight = 0
  identifier = "linkedin"
  name = "Linkedin"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-linkedin\"></i>"
  url = "https://www.linkedin.com/in/dawnarc/"
[[menu.links]]
  weight = 0
  identifier = "pinterest"
  name = "Pinterest"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-pinterest\"></i>"
  url = "https://www.pinterest.com/wangaiguo/"
[[menu.links]]
  weight = 0
  identifier = "steam"
  name = "Steam"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-steam\"></i>"
  url = "https://steamcommunity.com/id/dawnarc"
[[menu.links]]
  weight = 0
  identifier = "instagram"
  name = "Instagram"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-instagram\"></i>"
  url = "https://www.instagram.com/dawn_arc/"


[params]
  syntaxHighlighter = "highlight.js"

  customCSS = ["cdnjs.cloudflare.com/ajax/libs/highlight.js/11.6.0/styles/paraiso-light.min.css"]
 
  # Customize date format use to render blog post date, categories and other
  # You must use date format used by Go Time package https://golang.org/pkg/time/
  # Months (not work with short month like "jan", "feb", etc) are translated if translation exists on i18n folders
  # Default format is: January 2, 2006 
  # dateFormat = "2 January 2006"
  dateFormat = "Monday, 15:04, Jan 2, 2006"
	
  # Global keywords configuration. Following keywords will be add to every pages
  # keywords = ["development", "next-gen"]

  # Hide sidebar on all article page to let article take full width to improve reading, and enjoy wide images and cover images. (true: enable, false: disable)
  clearReading = true

  # Define categories will create hierarchy between parents: `categories = ["foo", "bar"]` will consider "bar" a sub-category of "foo". 
  # If false it will flat categories.
  hierarchicalCategories = false

  description = "Hugo tranquilpeak theme demo"

  # Customization
  # Define the behavior of the sidebar
  # 1: Display extra large sidebar on extra large screen, large sidebar on large screen,
  #    medium sidebar on medium screen and header bar on small screen and
  # extra large sidebar is swiped on extra large screen and large sidebar on all lower screen (default)
  # 2: Display large sidebar on large screen, medium sidebar on medium screen and
  #    header bar on small screen and large sidebar is swiped
  # 3: Display medium sidebar on large and medium screen and header bar on small screen and
  #    medium sidebar is swiped
  # 4: Display header bar on all screens, extra large sidebar is swiped on extra large screen and
  #    large sidebar is swiped on all lower screens
  # 5: Display header bar on all screens and large sidebar is swiped on large screen
  # 6: Display header bar on all screens and medium sidebar is swiped
  sidebarBehavior = 1

  # Your blog cover picture. I STRONGLY recommend you to use a CDN to speed up loading of pages.
  # There is many free CDN like Cloudinary or you can also use indirectly
  # by using services like Google Photos.
  # Current image is on AWS S3 and delivered by AWS CloudFront.
  # Otherwise put your image in folder `static/_images/` (development)  or in `source/assets/images/` if you can't or don't want to build the theme,
  # and use relative url : `your-image.png`
  coverImage = "cover-v1.2.0.jpg"

  # Display an image gallery at the end of a post which have photos variables (false: disabled, true: enabled)
  imageGallery = true

  # Display thumbnail image of each post on index pages (false: disabled, true: enabled)
  thumbnailImage = true
  # Display thumbnail image at the right of title in index pages (`right`, `left` or `bottom`)
  # Set this value to `right` if you have old posts to keep the old style on them
  # and define `thumbnailImagePosition` on a post to overwrite this setting
  thumbnailImagePosition = "bottom"
  # Automatically select the cover image or the first photo from the gallery of a post if there is no thumbnail image as the thumbnail image
  # Set this value to `true` if you have old posts that use the cover image or the first photo as the thumbnail image
  # and set `autoThumbnailImage` to `false` on a post to overwrite this setting
  autoThumbnailImage = true

  # Header configuration
  # The link at the right of the header is customizable
  # You can add a link (as an icon) at the right of the header instead of the author's gravatar image or author's picture.
  # By default, author's gravatar or author's picture is displayed.
  #     url: /#search
  #     icon: search
  #     class: st-search-show-outputs
  [params.header.rightLink]
    class = ""
    icon = ""
    url = "/#about"